import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav";
import img from './../public/vercel.svg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav/>
        <h1>Home Page</h1>
        <Image src={img} />
        <p>
          Fugiat dolore adipisicing labore dolor incididunt culpa dolor tempor
          excepteur enim. Esse occaecat enim et voluptate do. Eu exercitation
          reprehenderit aliqua Lorem tempor. Ut incididunt laborum nulla irure
          officia Lorem dolore velit officia laboris excepteur id minim ad. Quis
          dolore enim laboris ea laboris commodo enim occaecat. Proident elit eu
          mollit id anim nulla culpa do aliquip cupidatat irure ullamco. Veniam
          ullamco consectetur velit aute ea culpa et tempor deserunt amet aliqua
          ad voluptate fugiat.
        </p>
      </main>
    </div>
  );
}
